/**
 * Dashboard Component
 * Generated by Quantum Code Synthesis
 * A React dashboard with real-time data visualization
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
} from 'chart.js';
import { Line, Bar, Doughnut } from 'react-chartjs-2';

// Register Chart.js components
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement
);

// Types
interface DashboardData {
  timestamp: string;
  users: number;
  revenue: number;
  orders: number;
  category: string;
}

interface ChartData {
  labels: string[];
  datasets: Array<{
    label: string;
    data: number[];
    backgroundColor?: string;
    borderColor?: string;
    borderWidth?: number;
  }>;
}

interface DashboardProps {
  refreshInterval?: number;
  maxDataPoints?: number;
  theme?: 'light' | 'dark';
}

// Custom hooks
const useDashboardData = (refreshInterval: number = 30000) => {
  const [data, setData] = useState<DashboardData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      // In real implementation, this would fetch from API
      const mockData: DashboardData[] = [
        { timestamp: '2024-01-01', users: 1200, revenue: 45000, orders: 89, category: 'Electronics' },
        { timestamp: '2024-01-02', users: 1350, revenue: 52000, orders: 102, category: 'Books' },
        { timestamp: '2024-01-03', users: 1180, revenue: 48000, orders: 95, category: 'Clothing' },
        // ... more data points
      ];

      setData(mockData);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch data');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, refreshInterval);
    return () => clearInterval(interval);
  }, [fetchData, refreshInterval]);

  return { data, loading, error, refetch: fetchData };
};

// Main component
const DashboardComponent: React.FC<DashboardProps> = ({
  refreshInterval = 30000,
  maxDataPoints = 50,
  theme = 'light'
}) => {
  const { data, loading, error, refetch } = useDashboardData(refreshInterval);

  // Memoized chart data
  const chartData = useMemo((): ChartData => {
    const limitedData = data.slice(-maxDataPoints);

    return {
      labels: limitedData.map(d => new Date(d.timestamp).toLocaleDateString()),
      datasets: [
        {
          label: 'Users',
          data: limitedData.map(d => d.users),
          borderColor: 'rgb(75, 192, 192)',
          backgroundColor: 'rgba(75, 192, 192, 0.2)',
          borderWidth: 2,
        },
        {
          label: 'Revenue ($)',
          data: limitedData.map(d => d.revenue),
          borderColor: 'rgb(255, 99, 132)',
          backgroundColor: 'rgba(255, 99, 132, 0.2)',
          borderWidth: 2,
        },
      ],
    };
  }, [data, maxDataPoints]);

  // Revenue by category data
  const categoryData = useMemo(() => {
    const categoryTotals = data.reduce((acc, item) => {
      acc[item.category] = (acc[item.category] || 0) + item.revenue;
      return acc;
    }, {} as Record<string, number>);

    return {
      labels: Object.keys(categoryTotals),
      datasets: [{
        label: 'Revenue by Category',
        data: Object.values(categoryTotals),
        backgroundColor: [
          'rgba(255, 99, 132, 0.8)',
          'rgba(54, 162, 235, 0.8)',
          'rgba(255, 205, 86, 0.8)',
          'rgba(75, 192, 192, 0.8)',
          'rgba(153, 102, 255, 0.8)',
        ],
        borderWidth: 1,
      }],
    };
  }, [data]);

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top' as const,
      },
      title: {
        display: true,
        text: 'Dashboard Analytics',
      },
    },
    scales: {
      y: {
        beginAtZero: true,
      },
    },
  };

  const doughnutOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'right' as const,
      },
    },
  };

  // Summary statistics
  const summaryStats = useMemo(() => {
    if (data.length === 0) return null;

    const totalUsers = data.reduce((sum, d) => sum + d.users, 0);
    const totalRevenue = data.reduce((sum, d) => sum + d.revenue, 0);
    const totalOrders = data.reduce((sum, d) => sum + d.orders, 0);
    const avgOrderValue = totalOrders > 0 ? totalRevenue / totalOrders : 0;

    return {
      totalUsers,
      totalRevenue: totalRevenue.toLocaleString('en-US', {
        style: 'currency',
        currency: 'USD'
      }),
      totalOrders,
      avgOrderValue: avgOrderValue.toLocaleString('en-US', {
        style: 'currency',
        currency: 'USD'
      }),
    };
  }, [data]);

  if (loading) {
    return (
      <div className="dashboard-loading">
        <div className="loading-spinner"></div>
        <p>Loading dashboard data...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="dashboard-error">
        <h3>Error Loading Dashboard</h3>
        <p>{error}</p>
        <button onClick={refetch} className="retry-button">
          Retry
        </button>
      </div>
    );
  }

  return (
    <div className={`dashboard-container ${theme}`}>
      <header className="dashboard-header">
        <h1>Analytics Dashboard</h1>
        <div className="dashboard-controls">
          <button onClick={refetch} className="refresh-button">
            Refresh Data
          </button>
          <span className="last-updated">
            Last updated: {new Date().toLocaleTimeString()}
          </span>
        </div>
      </header>

      {summaryStats && (
        <section className="summary-stats">
          <div className="stat-card">
            <h3>Total Users</h3>
            <p className="stat-value">{summaryStats.totalUsers.toLocaleString()}</p>
          </div>
          <div className="stat-card">
            <h3>Total Revenue</h3>
            <p className="stat-value">{summaryStats.totalRevenue}</p>
          </div>
          <div className="stat-card">
            <h3>Total Orders</h3>
            <p className="stat-value">{summaryStats.totalOrders.toLocaleString()}</p>
          </div>
          <div className="stat-card">
            <h3>Avg Order Value</h3>
            <p className="stat-value">{summaryStats.avgOrderValue}</p>
          </div>
        </section>
      )}

      <section className="charts-section">
        <div className="chart-container">
          <h3>Trends Over Time</h3>
          <div className="chart-wrapper">
            <Line data={chartData} options={chartOptions} />
          </div>
        </div>

        <div className="chart-container">
          <h3>Revenue by Category</h3>
          <div className="chart-wrapper">
            <Doughnut data={categoryData} options={doughnutOptions} />
          </div>
        </div>
      </section>
    </div>
  );
};

// Styled components (CSS-in-JS approach)
const styles = `
.dashboard-container {
  padding: 20px;
  max-width: 1200px;
  margin: 0 auto;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.dashboard-container.dark {
  background-color: #1a1a1a;
  color: #ffffff;
}

.dashboard-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
  padding-bottom: 20px;
  border-bottom: 1px solid #e0e0e0;
}

.dashboard-controls {
  display: flex;
  align-items: center;
  gap: 15px;
}

.refresh-button, .retry-button {
  padding: 8px 16px;
  background-color: #007bff;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
}

.refresh-button:hover, .retry-button:hover {
  background-color: #0056b3;
}

.summary-stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
  margin-bottom: 40px;
}

.stat-card {
  background: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  text-align: center;
}

.stat-card h3 {
  margin: 0 0 10px 0;
  color: #666;
  font-size: 14px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.stat-value {
  font-size: 24px;
  font-weight: bold;
  color: #333;
  margin: 0;
}

.charts-section {
  display: grid;
  grid-template-columns: 2fr 1fr;
  gap: 30px;
}

.chart-container {
  background: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.chart-container h3 {
  margin: 0 0 20px 0;
  color: #333;
}

.chart-wrapper {
  height: 300px;
  position: relative;
}

.dashboard-loading, .dashboard-error {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 400px;
  text-align: center;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #007bff;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.last-updated {
  font-size: 12px;
  color: #666;
}

/* Dark theme overrides */
.dashboard-container.dark .stat-card {
  background: #2d2d2d;
  color: #ffffff;
}

.dashboard-container.dark .chart-container {
  background: #2d2d2d;
  color: #ffffff;
}

.dashboard-container.dark .dashboard-header {
  border-bottom-color: #404040;
}
`;

// Export styles for external use
export const dashboardStyles = styles;

// Default export
export default DashboardComponent;
